### ISSUE TITLE
Cannot close modal on mobile

### ISSUE THREAD

**Issue by vcavallo** [dalten-collective/gora#1]
maybe i'm a dummy. but i don't see a way to close the gora modal on mobile aside from refreshing

**Comment by rabsef-bicrym** [comment]
I am able to close modal on mobile by clicking outside of the square - do you think it warrants having an obvious close button within the modal? @vcavallo

**Comment by vcavallo** [comment]
Hey sorry forgot to reply here.

I'm using the "add to home screen" Safari feature on iOS. in that particular browser context, clicking outside of the modal does **not** close it (or perhaps the click is not being registered as `outside`, maybe there's an overlay or something).
Having a little "close" `X` in the upper corner of the modal is probably the right thing to do UX/accessibility-wise, but I also think we have bigger fish to fry so I don't want this to distract. I'll add a project item at the very bottom and close this issue.
