### ISSUE TITLE
Option: Remove Host ability to dictate public

### ISSUE THREAD

**Issue by rabsef-bicrym** [dalten-collective/gora#8]
Currently, host and client must mark a gora as public for it to appear in the public list - this has resulted in a lot of confusion and extraneous code, to boot.

Should we allow users to mark ANY gora _they own_ as public? Is there still a good rationale for allowing a host to not publicize their secret gora?

**Comment by vcavallo** [comment]
A secret's safety is only as secure as your trust in the person to whom you grant knowledge of the secret.

**Comment by rabsef-bicrym** [comment]
The ability to make gorae public has been democratized.
